### ISSUE TITLE
Using webpack@next

### ISSUE THREAD

**Issue by chakler** [grayscaleltd/grayscale-wordpress-scaffolding#2]
After doing some tests, seems like `webpack@next` is the most suitable for our current development.

It’s not ideal to keep the `next` tag as the required version in `package.json` though so this must be updated when webpack 5 goes live.

**Comment by kchan825** [comment]
Note that with the current setup, using the `next` tag will compile files that are not compatible with IE. Make sure it is not listed as a supported browser in the project.

**Comment by chakler** [comment]
@ajman825 What are the errors you’re getting?

**Comment by kchan825** [comment]
Not per se error, just incompatible with IE. Obvious symptom is arrow functions are not turned into function declaration.

**Comment by chakler** [comment]
I wonder if it's a webpack issue, could be compatibility problem between webpack 5 and Babel.

Will investigate further.

**Comment by chakler** [comment]
Aha might be this: https://webpack.js.org/migrate/5/#turn-off-es2015-syntax-in-runtime-code-if-necessary
