### ISSUE TITLE
Disable output of LICENSE file

### ISSUE THREAD

**Issue by kchan825** [grayscaleltd/grayscale-wordpress-scaffolding#4]
Remove the extra LICENSE file (e.g. application.LICENSE.js.txt) generated on compilation.

**Comment by chakler** [comment]
Need more research but might be caused by this: https://webpack.js.org/plugins/terser-webpack-plugin/

**Comment by kchan825** [comment]
Apparently there is this whole [discussion](https://github.com/facebook/create-react-app/issues/6441) that:

1. Licences stripped out from the bundled output is probably good for performance — reduced file size;
2. Licences information are then retained using a separate file;
3. It used to be a .LICENCE file, but [not all servers are configured to serve it](https://blog.johnnyreilly.com/2020/01/license-to-kill-your-pwa.html) (and hence breaking things), the plugin changed it to a .TXT file

At the end of the day, if we want to kill the file, we need to [turn it off](https://webpack.js.org/plugins/terser-webpack-plugin/#extractcomments) in the Terser plugin.
